### ISSUE TITLE
dde-grand-search: 其它发行版移植打包

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/open-source-students#61]
这个是刚刚迁移到社区并且对外开源的组件，应该各个平台都没打包，可以考虑打包。

**Comment by SamLukeYes** [comment]
已打包上传至 AUR：https://aur.archlinux.org/packages/deepin-grand-search-git

**Comment by msojocs** [comment]
- [ ] AppImage
- [ ] Flatpak
