### ISSUE TITLE
deepin-gomoku: 修改 README

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/open-source-students#63]
项目： https://github.com/linuxdeepin/deepin-gomoku

这个项目最近将开发流程迁移到了 GitHub，可以考虑根据 [README 模板](https://github.com/linuxdeepin/developer-center/wiki/README-Template) 来编辑这个项目的 README 使其变得更有用。

这个项目 README 目前存在的问题：

- 格式是不对的，无法渲染出显示正常的排版

**Comment by Ronghzhe** [comment]
修改 README https://github.com/linuxdeepin/deepin-gomoku/pull/2

**Comment by BLumia** [comment]
这个项目的 CI 检查有点问题，我们处理过后再进行合入

**Comment by BLumia** [comment]
已经合入，故关闭此 issue 🎉
